FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

# Install Python and OpenCV runtime libraries
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        python3 \
        python3-dev \
        python3-pip \
        python3-venv \
        libgl1 \
        libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/app
ADD ./src ./
ADD ./requirements-gpu.txt ./requirements-gpu.txt

RUN python3 -m pip install --upgrade pip && \
    pip install -r requirements-gpu.txt

CMD ["python3", "main.py"]
